# Generated by Django 2.2.6 on 2019-11-12 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compte', '0003_note_enseignant'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='document',
            field=models.FileField(default=1, upload_to='documents/'),
            preserve_default=False,
        ),
    ]
